### ISSUE TITLE
outdated example on Readme?

### ISSUE THREAD

**Issue by Zincr0** [finiteautomata/pysentimiento#3]
Following the example you will get

```
In [1]: from pysentimiento import SentimentAnalyzer

In [2]: analyzer = SentimentAnalyzer(lang="es")
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-2-479bef79285e> in <module>
----> 1 analyzer = SentimentAnalyzer(lang="es")

TypeError: __init__() got an unexpected keyword argument 'lang'
```
Edit: looks like the pip version is different to the one on github

**Comment by finiteautomata** [comment]
Hum, have you installed `0.2.0`? The `lang` argument was introduced in that version

**Comment by Zincr0** [comment]
for some reason pip install an old version by default, ended up cloning this repo

**Comment by finiteautomata** [comment]
Strange. I just tested installing it on `3.8.5` and it correctly installs `0.2.0` version. Check you are not specifying a version and just use `pip install pysentimiento`

**Comment by finiteautomata** [comment]
Ok, I guess it was a confusion. Closing this
